version: "3"

services:
  server:
    build: .
    restart: unless-stopped
    environment:
      TZ: Europe/Rome
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - reverse-proxy

networks:
  reverse-proxy: { external: true }

volumes:
  caddy_data:
  caddy_config:
